# Charger les bibs

In [23]:
from tensorflow.keras.models import load_model
from keras.preprocessing import image
from tensorflow.keras import optimizers
from PIL import Image
import numpy as np
import glob
import os


# Paramétres de l'inférence

In [24]:
model_path = './Modelcpp1.h5'
img_path = 'C:/Users/adm_ael-filou/Desktop/Exemple_Anis/prediction/2.png'
folder_path ='./all/'
folder_new_img_path = "./prediction/"
pred =['Compound Switch','Oblique Crossing','Single Switch']


# Charger et compiler le modéle

In [25]:
def load_and_compile(model_path):
    
    # load the trained model
    opt = optimizers.Adam(learning_rate =0.001)
    model = load_model(model_path)
    model.compile(loss='categorical_crossentropy',
                  optimizer=opt,
                  metrics=['accuracy'])
    return model

# Pré traitement des images

In [26]:
def pre_teret2(img,min_size=256, fill_color=(0, 0, 0)):
    
    old_size = img.size  # old_size[0] is in (width, height) format
    ratio = float(min_size)/max(old_size)
    new_size = tuple([int(x*ratio) for x in old_size])
    # thumbnail is a in-place operation
    img = img.resize(new_size)
    # create a new image and paste the resized on it
    new_im = Image.new("RGB", (min_size, min_size))
    new_im.paste(img, ((min_size-new_size[0])//2,
                        (min_size-new_size[1])//2))
        
    return new_im

In [27]:
model = load_and_compile(model_path)

# Inférer une seule image

In [28]:
def infer_one_img(model,pred,img_path):
    test_image = pre_teret2(Image.open(img_path))
    #test_image.show()
    test_image = image.img_to_array(test_image)
    test_image = np.expand_dims(test_image, axis = 0)
    result = model.predict(test_image)
    return(pred[np.argmax(result)])
res = infer_one_img(model,pred,img_path)
print(res)

Single Switch


# Inférer les dossiers test

In [15]:
def infer_test_folders(model,pred,folder_path):
    for i in pred:
        print(f"-------les images du dossier {i} --------------")
        for file in glob.iglob(os.path.join(folder_path+i,"*.png")):
            test_image = pre_teret2(Image.open(file))
            test_image = image.img_to_array(test_image)
            test_image = np.expand_dims(test_image, axis = 0)
            result = model.predict(test_image)
            print(f"here the result {result} and the pred {pred[np.argmax(result)]}")
            if (pred[np.argmax(result)] != i):
                print(file)
                print(f"fausse préduction p = {pred[np.argmax(result)]} GT = {i}")
                print(result)
                print("----------------------------------------------------------")
infer_test_folders(model,pred,folder_path)

-------les images du dossier Compound Switch --------------
-------les images du dossier Oblique Crossing --------------
-------les images du dossier Single Switch --------------


In [16]:
['Compound Switch','Oblique Crossing','Single Switch']

['Compound Switch', 'Oblique Crossing', 'Single Switch']

# Inférer les nouvelles images

In [6]:
def infer_new_imgs(model,pred,folder_new_img_path):
    for file in glob.iglob(os.path.join(folder_new_img_path,"*.png")):
        test_image = pre_teret2(Image.open(file))
        #test_image.show()
        test_image = image.img_to_array(test_image)
        test_image = np.expand_dims(test_image, axis = 0)
        result = model.predict(test_image)
        print("----------------------------------------------------------")
        print(file)
        print(f"here the result {result} and the pred {pred[np.argmax(result)]}")
infer_new_imgs(model,pred,folder_new_img_path)

----------------------------------------------------------
./prediction\1.png
here the result [[9.9734324e-01 5.3560365e-09 2.6568095e-03]] and the pred Compound Switch
----------------------------------------------------------
./prediction\10.png
here the result [[2.0820050e-07 5.1755596e-05 9.9994802e-01]] and the pred Single Switch
----------------------------------------------------------
./prediction\11.png
here the result [[3.8961221e-07 9.9485767e-01 5.1419646e-03]] and the pred Oblique Crossing
----------------------------------------------------------
./prediction\12.png
here the result [[1.9345637e-07 7.4223476e-06 9.9999237e-01]] and the pred Single Switch
----------------------------------------------------------
./prediction\13.png
here the result [[3.1027639e-06 4.4507154e-09 9.9999690e-01]] and the pred Single Switch
----------------------------------------------------------
./prediction\14.png
here the result [[1.06591125e-10 1.00000000e+00 1.35810598e-08]] and the pred

In [1]:
from PIL import Image, ImageOps
import cv2
import numpy as np 

def pretraitement (img,desired_size = 256):
     old_size = img.shape[:2] # old_size is in (height, width) format
     ratio = float(desired_size)/max(old_size)
     new_size = tuple([int(x*ratio) for x in old_size])
     img = cv2.resize(img, (new_size[1], new_size[0]))
     delta_w = desired_size - new_size[1]
     delta_h = desired_size - new_size[0]
     top, bottom = delta_h//2, delta_h-(delta_h//2)
     left, right = delta_w//2, delta_w-(delta_w//2)
     color = [0, 0, 0]
     new_im = cv2.copyMakeBorder(img, top, bottom, left, right, cv2.BORDER_CONSTANT,value=color)
     return new_im


In [2]:
image = pretraitement(cv2.imread('C:/Users/adm_ael-filou/Desktop/Exemple_Anis/prediction/22.png'))

In [3]:
image.shape


(256, 256, 3)

In [61]:
import tensorflow as tf
import numpy as np
def recognize(jpg_path, pb_file_path):
  with tf.Graph().as_default():
    output_graph_def = tf.compat.v1.GraphDef()
    with open(pb_file_path, 'rb') as f:
      output_graph_def.ParseFromString(f.read())
      tensors = tf.import_graph_def(output_graph_def, name='')
      print('tensors: ', tensors)
    with tf.compat.v1.Session() as sess:
      init = tf.compat.v1.global_variables_initializer()
      sess.run(init)
      op = sess.graph.get_operations()
      for i, m in enumerate(op):
        print('op{}: '.format(i), m.values())
      input_x = sess.graph.get_tensor_by_name('yourInputName:0')
      print('input_X: ', input_x)
      out_softmax = sess.graph.get_tensor_by_name('sequential/dense_1/Softmax:0')
      print('Output:', out_softmax)
      img = cv2.imread(jpg_path)
      img = cv2.resize(img, (256, 256))
      img = img.astype(np.float32)
      #img = 1-img/255
      print('img data type: ', img.dtype)
      for row in range(256):
        for col in range(256):
          if col!=255:
            print(img[row][col], ' ', end='')
          else:
            print(img[row][col])
      img_out_softmax = sess.run(out_softmax, feed_dict={input_x: np.reshape(img, (1, 256, 256, 3))})
      print('img_out_softmax: ', img_out_softmax)
      for i, prob in enumerate(img_out_softmax[0]):
        print('class{} prob: {}'.format(i, prob))
      prediction_labels = np.argmax(img_out_softmax, axis=1)
      print('Final class is: ', prediction_labels)
      print('prob of label: ', img_out_softmax[0, prediction_labels])
pb_path = './frozen_models/frozen_graph.pb'
img = './1.png'
recognize(img, pb_path)

tensors:  None
op0:  (<tf.Tensor 'yourInputName:0' shape=(None, 256, 256, 3) dtype=float32>,)
op1:  (<tf.Tensor 'sequential/conv2d/Conv2D/ReadVariableOp/resource:0' shape=(3, 3, 3, 16) dtype=float32>,)
op2:  (<tf.Tensor 'sequential/conv2d/Conv2D/ReadVariableOp:0' shape=(3, 3, 3, 16) dtype=float32>,)
op3:  (<tf.Tensor 'sequential/conv2d/Conv2D:0' shape=(None, 254, 254, 16) dtype=float32>,)
op4:  (<tf.Tensor 'sequential/conv2d/BiasAdd/ReadVariableOp/resource:0' shape=(16,) dtype=float32>,)
op5:  (<tf.Tensor 'sequential/conv2d/BiasAdd/ReadVariableOp:0' shape=(16,) dtype=float32>,)
op6:  (<tf.Tensor 'sequential/conv2d/BiasAdd:0' shape=(None, 254, 254, 16) dtype=float32>,)
op7:  (<tf.Tensor 'sequential/conv2d/Relu:0' shape=(None, 254, 254, 16) dtype=float32>,)
op8:  (<tf.Tensor 'sequential/max_pooling2d/MaxPool:0' shape=(None, 127, 127, 16) dtype=float32>,)
op9:  (<tf.Tensor 'sequential/batch_normalization/ReadVariableOp/resource:0' shape=(16,) dtype=float32>,)
op10:  (<tf.Tensor 'sequentia

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [18. 18. 18.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [45. 45. 45.]  [255. 255. 255.]  [253. 253. 253.]  [233. 233. 233.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [3. 3. 3.]  [235. 235. 235.]  [251. 251. 251.]  [19. 19. 19.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [91. 91. 91.]  [182. 182. 182.]  [123. 123. 123.]  [14. 14. 14.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [28. 28. 28.]  [181. 181. 181.]  [255. 255. 255.]  [252. 252. 252.]  [184. 184. 184.]  [79. 79. 79.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [71. 71. 71.]  [228. 228. 228.]  [69. 69. 69.]  [18. 18. 18.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [25. 25. 25.]  [255. 255. 255.]  [253. 253. 253.]  [255. 255. 255.]  [255. 255. 255.]  [255. 255. 255.]  [203. 203. 203.]  [34. 34. 34.]  [9. 9. 9.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [240. 240. 240.]  [255. 255. 255.]  [43. 43. 43.]  [11. 11. 11.]  [0. 0. 0.]  [40. 40. 40.]  [184. 184. 184.]  [234. 234. 234.]  [77. 77. 77.]  [0. 0. 0.]  [2. 2. 2.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [231. 231. 231.]  [217. 217. 217.]  [239. 239. 239.]  [255. 255. 255.]  [231. 231. 231.]  [62. 62. 62.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [74. 74. 74.]  [165. 165. 165.]  [255. 255. 255.]  [255. 255. 255.]  [165. 165. 165.]  [81. 81. 81.]  [255. 255. 255.]  [248. 248. 248.]  [187. 187. 187.]  [233. 233. 233.]  [176. 176. 176.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [64. 64. 64.]  [153. 153. 153.]  [250. 250. 250.]  [255. 255. 255.]  [205. 205. 205.]  [175. 175. 175.]  [170. 1

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [44. 44. 44.]  [68. 68. 68.]  [6. 6. 6.]  [63. 63. 63.]  [228. 228. 228.]  [108. 108. 108.]  [255. 255. 255.]  [255. 255. 255.]  [243. 243. 243.]  [85. 85. 85.]  [229. 229. 229.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [37. 37. 37.]  [111. 111. 111.]  [178. 178. 178.]  [76. 76. 76.]

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [12. 12. 12.]  [209. 209. 209.]  [254. 254. 254.]  [178. 178. 178.]  [250. 250. 250.]  [255. 255. 255.]  [31. 31. 31.]  [71. 71. 71.]  [20. 20. 20.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [112. 112. 112.]  [199. 199. 199.]  [255. 255. 255.]  [255. 255. 255.]  [255. 255. 255.]  [255. 255. 255.]  [255. 255. 255.]  [150. 150. 150.]  [39. 39. 39.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [59. 59. 59.]  [122. 122. 122.]  [157. 157. 157.]  [241. 241. 241.]  [255. 255. 255.]  [255. 255. 255.]  [255. 255. 255.]  [160. 160. 160.]  [53. 53. 53.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [35. 35. 35.]  [190. 190. 190.]  [255. 255. 255.]  [255. 255. 255.]  [255. 255. 255.]  [232. 232. 232.]  [174. 174. 174.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [32. 32. 32.]  [113. 113. 113.]  [222. 222. 222.]  [255. 255. 255.]  [195. 195. 195.]  [87. 87. 87.]  [219. 219. 219.]  [255. 255. 255.]  [237. 237. 237.]  [192. 192. 192.]  [0. 0. 0.]  [0. 0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [127. 127. 127.]  [227. 227. 227.]  [255. 255. 255.]  [255. 255. 255.]  [255. 255. 255.]  [190. 190. 190.]  [70. 70. 70.]  [12. 12. 12.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [3. 3. 3.]  [118. 118. 118.]  [57. 57. 57.]  [236. 236. 236.]  [86. 86. 86.]  [17. 17. 17.]  [0. 0. 0.]  [

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [169. 169. 169.]  [109. 109. 109.]  [207. 207. 207.]  [141. 141. 141.]  [142. 142. 142.]  [255. 255. 255.]  [190. 190. 190.]  [99. 99. 99.]  [108. 108. 108.]  [174. 174. 174.]  [74. 74. 74.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [26.

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [116. 116. 116.]  [240. 240. 240.]  [189. 189. 189.]  [188. 188. 188.]  [183. 183. 183.]  [91. 91. 91.]  [255. 255. 255.]  [193. 193. 193.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [45. 45. 45.]  [0. 0. 0.]  [230. 230. 230.]  [155. 155. 155.]  [202. 202. 202.]  [54. 54. 54.]  [15. 15. 15.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [59. 59. 59.]  [251. 251. 251.]  [180. 180. 180.]  [93. 93. 93.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [83. 83. 83.]  [96. 96. 96.]  [18. 18. 18.]  [98. 98. 98.]  [200. 200. 200.]  [255. 255. 255.]  [255. 255. 255.]  [255. 255. 255.]  [255. 255. 255.]  [228. 228. 228.]  [210. 210. 210.]  [206. 206. 206.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [47. 47. 47.]  [180. 180. 180.]  [235. 2

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [18. 18. 18.]  [9. 9. 9.]  [37. 37. 37.]  [142. 142. 142.]  [101. 101. 101.]  [255. 255. 255.]  [255. 255. 255.]  [255. 255. 255.]  [255. 255. 255.]  [30. 30. 30.]  [241. 241. 241.]  [116. 116. 116.]  [20. 20. 20.]  [0. 0. 0.]  [6. 6. 6.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [210. 210. 210.]  [242. 242. 242.]  [255. 255. 255.]  [206. 206. 206.]  [254. 254. 254.]  [235. 235. 235.]  [168. 168. 168.]

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [23. 23. 23.]  [0. 0. 0.]  [

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [215. 215. 215.]  [243. 243. 243.]  [154. 154. 154.]  [191. 191. 191.]  [67. 67. 67.]  [18. 18. 18.]

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [66. 66. 66.]  [

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

[0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 0. 0.]  [0. 

In [1]:
from keras import backend as K
# This line must be executed before loading Keras model.
K.set_learning_phase(0)
from keras.models import load_model
model = load_model('./ModelFinale.h5')

C:\Users\adm_ael-filou\AppData\Roaming\Python\Python38\site-packages\keras\backend.py:400: UserWarning: `tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
  warnings.warn('`tf.keras.backend.set_learning_phase` is deprecated and '


In [12]:
from tensorflow import keras
import tensorflow as tf
from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2
import numpy as np


model = keras.models.load_model('./ModelFinale.h5')

# Convert Keras model to ConcreteFunction
full_model = tf.function(lambda x: model(x))
full_model = full_model.get_concrete_function(
    x=tf.TensorSpec(model.inputs[0].shape, model.inputs[0].dtype))

# Get frozen ConcreteFunction
frozen_func = convert_variables_to_constants_v2(full_model)
frozen_func.graph.as_graph_def()

# inspect the layers operations inside your frozen graph definition and see the name of its input and output tensors
layers = [op.name for op in frozen_func.graph.get_operations()]
print("-" * 50)
print("Frozen model layers: ")
for layer in layers:
    print(layer)

print("-" * 50)
print("Frozen model inputs: ")
print(frozen_func.inputs)
print("Frozen model outputs: ")
print(frozen_func.outputs)

# Save frozen graph from frozen ConcreteFunction to hard drive
# serialize the frozen graph and its text representation to disk.
tf.io.write_graph(graph_or_graph_def=frozen_func.graph,
                  logdir="./frozen_models",
                  name="simple_frozen_graph.pb",
                  as_text=False)

#Optional
tf.io.write_graph(graph_or_graph_def=frozen_func.graph,
                  logdir="./frozen_models",
                  name="simple_frozen_graph.pbtxt",
                as_text=True)

model.summary()


--------------------------------------------------
Frozen model layers: 
x
sequential/conv2d/Conv2D/ReadVariableOp/resource
sequential/conv2d/Conv2D/ReadVariableOp
sequential/conv2d/Conv2D
sequential/conv2d/BiasAdd/ReadVariableOp/resource
sequential/conv2d/BiasAdd/ReadVariableOp
sequential/conv2d/BiasAdd
sequential/conv2d/Relu
sequential/max_pooling2d/MaxPool
sequential/batch_normalization/ReadVariableOp/resource
sequential/batch_normalization/ReadVariableOp
sequential/batch_normalization/ReadVariableOp_1/resource
sequential/batch_normalization/ReadVariableOp_1
sequential/batch_normalization/FusedBatchNormV3/ReadVariableOp/resource
sequential/batch_normalization/FusedBatchNormV3/ReadVariableOp
sequential/batch_normalization/FusedBatchNormV3/ReadVariableOp_1/resource
sequential/batch_normalization/FusedBatchNormV3/ReadVariableOp_1
sequential/batch_normalization/FusedBatchNormV3
sequential/conv2d_1/Conv2D/ReadVariableOp/resource
sequential/conv2d_1/Conv2D/ReadVariableOp
sequential/conv2d

In [1]:
from keras.models import load_model
model = load_model('./keras_model.h5')
print(model.outputs)
# [<tf.Tensor 'dense_2/Softmax:0' shape=(?, 10) dtype=float32>]
print(model.inputs)
# [<tf.Tensor 'conv2d_1_input:0' shape=(?, 28, 28, 1) dtype=float32>]

[<KerasTensor: shape=(None, 3) dtype=float32 (created by layer 'dense_1')>]
[<KerasTensor: shape=(None, 256, 256, 3) dtype=float32 (created by layer 'conv2d_input')>]


In [2]:
from keras.models import load_model
model = load_model('./ModelFinale.h5')
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [3]:

model.save('test.h5', include_optimizer=False)

